# Alter schema for the configuration files of the System module.
system.performance:
  mapping:
    gzip_html:
      type: mapping
      label: 'Gzip html performance settings'
      mapping:
        gzip_html:
          type: boolean
          label: 'Gzip html'
